"""Add content column to pdfs table

Revision ID: 965a9221f015
Revises: d9c2f03e1159
Create Date: 2024-09-07 21:13:15.271607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965a9221f015'
down_revision: Union[str, None] = 'd9c2f03e1159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('content', sa.LargeBinary(), nullable=True))
    op.drop_column('pdfs', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pdfs', 'content')
    # ### end Alembic commands ###
