"""Create PDF table

Revision ID: d9c2f03e1159
Revises: 
Create Date: 2024-09-07 12:47:01.403711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c2f03e1159'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdfs_filename'), 'pdfs', ['filename'], unique=False)
    op.create_index(op.f('ix_pdfs_id'), 'pdfs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdfs_id'), table_name='pdfs')
    op.drop_index(op.f('ix_pdfs_filename'), table_name='pdfs')
    op.drop_table('pdfs')
    # ### end Alembic commands ###
